// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormInput: typeof import('./components/FormInput.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PostWriter: typeof import('./components/PostWriter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./components/SignupForm.vue')['default']
    TimeLine: typeof import('./components/TimeLine.vue')['default']
    TimelineItem: typeof import('./components/TimelineItem.vue')['default']
  }
}
